# TEMPLATE-APP: This is set as a reasonable default, feel free to change.

name: {APP-NAME}-app
namespace: kube-system
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/{APP-NAME}-app
  tag: v0.0.1
  pullPolicy: IfNotPresent
